env:
  REPOSITORY: flchub
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

name: publish
on: [push]
jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    steps:
        # выполняет клонирование репозитория на машину, где выполняется процесс сборки (агент GitHub Actions)
        - uses: actions/checkout@v4 # Checking out the repo

        # авторизацию в Docker-реестре (GitHub Container Registry — GHCR),
        # чтобы можно было загружать (push) или скачивать (pull) Docker-образы из этого реестра
        - name: Log in to the Container registry
          uses: docker/login-action@v2 # авторизация в Docker-реестра GHCR
          with:
            registry: ${{ env.REGISTRY }} # конкретный Docker-реестр - GHCR
            username: ${{ github.actor }} # данные для авторизации в реестре
            password: ${{ secrets.GITHUB_TOKEN }}

        # видимо, это что-то, что просто нужно сделать (возможно, какой-то инструмент для дальнейшей сборки докер-образов)
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        # сборка образа для фронта
        - name: Build and push Docker images
          uses: docker/build-push-action@v3
          with:
            context: ./frontend # где конкретно фронтенд
            file: ./frontend/Dockerfile
            push: true
            tags: ghcr.io/${{ env.REPOSITORY }}/film_frontend:${{ github.sha }}
        
        # сборка образа для бэкенда
        - name: Build and push Docker images
          uses: docker/build-push-action@v3
          with:
            context: ./backend # где конкретно бэкенд
            file: ./backend/Dockerfile
            push: true
            tags: ghcr.io/${{ env.REPOSITORY }}/film_backend:${{ github.sha }}
        
        # сборка образа для nginx
        - name: Build and push nginx Docker image
          uses: docker/build-push-action@v3
          with:
            context: ./nginx
            file: ./nginx/Dockerfile
            push: true
            tags: ghcr.io/${{ env.REPOSITORY }}/film_nginx:${{ github.sha }}